"""Promotes app-added titles into index.html's canonical ITEMS array.

Titles added through the app land in customItems, which lives only in the
live Artifact's published state. streaming-tracker never sees that — it
reads this repo's committed ITEMS array — so anything added via the app is
invisible to it until promoted here.

"Promote" means: fully-enriched items move out of customItems and into a
marked block inside ITEMS, and the app-data blob this writes back keeps
only the still-pending ones. Items must not live in both places at once —
the app renders ITEMS.concat(customItems), so anything in both shows twice.

Run enrich_pending.py first; items still marked p:true (no TMDb match yet)
stay in customItems for the next run rather than being promoted without a
type or genre, which would leave them unrenderable in both tabs.

Idempotent: the ITEMS block is replaced wholesale each run, never appended
to, so re-running or skipping runs both self-correct.

Usage:
    python3 sync_customitems.py app_data.json
"""
import json
import re
import sys
from pathlib import Path

INDEX_HTML = Path(__file__).parent / "index.html"
START_MARKER = "// ---- SYNCED-FROM-LIVE-APP (auto-generated by scheduled sync; do not hand-edit) ----"
END_MARKER = "// ---- END SYNCED-FROM-LIVE-APP ----"
APP_DATA_RE = re.compile(
    r'(<script type="application/json" id="app-data">)(.*?)(</script>)', re.S
)


def format_item(item):
    fields = ", ".join(
        f"{key}:{json.dumps(item.get(key), ensure_ascii=False)}"
        for key in ("y", "c", "t", "d", "w", "g", "s")
    )
    return f"{{{fields}}},"


def build_block(items):
    return "\n".join([START_MARKER] + [format_item(i) for i in items] + [END_MARKER])


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 sync_customitems.py app_data.json", file=sys.stderr)
        sys.exit(1)

    data_path = Path(sys.argv[1])
    app_data = json.loads(data_path.read_text())
    custom_items = app_data.get("customItems", [])

    promoted = [i for i in custom_items if not i.get("p")]
    still_pending = [i for i in custom_items if i.get("p")]

    src = INDEX_HTML.read_text()

    # Existing promoted titles stay put; this run's are appended to them.
    existing = []
    if START_MARKER in src:
        block = src[src.index(START_MARKER) + len(START_MARKER) : src.index(END_MARKER)]
        existing = [line for line in block.strip().splitlines() if line.strip()]

    known = set(existing)
    new_lines = [format_item(i) for i in promoted]
    merged = existing + [line for line in new_lines if line not in known]
    new_block = "\n".join([START_MARKER] + merged + [END_MARKER])

    if START_MARKER in src:
        start = src.index(START_MARKER)
        end = src.index(END_MARKER) + len(END_MARKER)
        updated = src[:start] + new_block + src[end:]
    else:
        marker = "\n];"
        idx = src.index(marker, src.index("const ITEMS = ["))
        updated = src[:idx] + "\n\n" + new_block + src[idx:]

    # Promoted items now live in ITEMS, so they must be dropped from the
    # app-data blob or the app would render each of them twice.
    new_app_data = {"overrides": app_data.get("overrides", {}), "customItems": still_pending}
    replacement_json = json.dumps(new_app_data)
    if not APP_DATA_RE.search(updated):
        print("Could not find the app-data script tag in index.html", file=sys.stderr)
        sys.exit(1)
    updated = APP_DATA_RE.sub(
        lambda m: m.group(1) + replacement_json.replace("\\", "\\\\") + m.group(3), updated, count=1
    )

    if updated == src:
        print("unchanged")
        return

    INDEX_HTML.write_text(updated)
    data_path.write_text(json.dumps(new_app_data, indent=2))
    print(
        f"promoted {len(promoted)} title(s) into ITEMS "
        f"({len(merged)} total synced); {len(still_pending)} still pending"
    )


if __name__ == "__main__":
    main()
