"""Syncs the live Artifact's customItems into index.html's committed ITEMS
array, so streaming-tracker (which only reads this repo, never the live
app) can see titles added through the app's "+" button.

Read-only against the live app: this never republishes or modifies the
live artifact, only this repo's index.html. Safe to run unattended.

Idempotent: each run *replaces* the synced block between the two marker
comments with the current customItems, rather than appending, so it's
self-correcting regardless of how long it's been since the last sync.

Usage:
    python3 sync_customitems.py app_data.json
    # app_data.json is the {"overrides": {...}, "customItems": [...]} blob
    # from the live artifact's <script id="app-data"> tag.

Exits 0 with "changed" or "unchanged" printed to stdout; the caller decides
whether to commit.
"""
import json
import sys
from pathlib import Path

INDEX_HTML = Path(__file__).parent / "index.html"
START_MARKER = "// ---- SYNCED-FROM-LIVE-APP (auto-generated by scheduled sync; do not hand-edit) ----"
END_MARKER = "// ---- END SYNCED-FROM-LIVE-APP ----"


def format_item(item):
    fields = ", ".join(
        f"{key}:{json.dumps(item.get(key))}" for key in ("y", "c", "t", "d", "w", "g", "s")
    )
    return f"{{{fields}}},"


def build_block(custom_items):
    lines = [START_MARKER]
    lines.extend(format_item(item) for item in custom_items)
    lines.append(END_MARKER)
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 sync_customitems.py app_data.json", file=sys.stderr)
        sys.exit(1)

    app_data = json.loads(Path(sys.argv[1]).read_text())
    custom_items = app_data.get("customItems", [])
    new_block = build_block(custom_items)

    src = INDEX_HTML.read_text()

    if START_MARKER in src:
        start = src.index(START_MARKER)
        end = src.index(END_MARKER) + len(END_MARKER)
        updated = src[:start] + new_block + src[end:]
    else:
        # First run: insert just before the ITEMS array's closing "];".
        marker = "\n];"
        idx = src.index(marker, src.index("const ITEMS = ["))
        updated = src[:idx] + "\n\n" + new_block + src[idx:]

    if updated == src:
        print("unchanged")
        return

    INDEX_HTML.write_text(updated)
    print(f"changed ({len(custom_items)} synced item(s))")


if __name__ == "__main__":
    main()
