"""Promotes app-added titles into index.html's canonical ITEMS array.

Titles added through the app land in customItems, which lives only in the
live Artifact's published state. streaming-tracker never sees that — it
reads this repo's committed ITEMS array — so anything added via the app is
invisible to it until promoted here.

"Promote" means: fully-enriched items move out of customItems and into a
marked block inside ITEMS, and the app-data blob this writes back keeps
only the still-pending ones. Items must not live in both places at once —
the app renders ITEMS.concat(customItems), so anything in both shows twice.

synced_items.json is the source of truth for what has been promoted;
the ITEMS block is regenerated from it wholesale each run. Re-promoting a
title that's already there updates it in place (keyed on type + title)
rather than appending a second copy, so a later run that adds a score to an
existing entry corrects it instead of duplicating it.

Run enrich_pending.py first; items still marked p:true (no TMDb match yet)
stay in customItems for the next run rather than being promoted without a
type or genre, which would leave them unrenderable in both tabs.

Usage:
    python3 sync_customitems.py app_data.json
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
INDEX_HTML = ROOT / "index.html"
SYNCED_ITEMS = ROOT / "synced_items.json"
START_MARKER = "// ---- SYNCED-FROM-LIVE-APP (auto-generated by scheduled sync; do not hand-edit) ----"
END_MARKER = "// ---- END SYNCED-FROM-LIVE-APP ----"
APP_DATA_RE = re.compile(
    r'(<script type="application/json" id="app-data">)(.*?)(</script>)', re.S
)
FIELDS = ("y", "c", "t", "d", "w", "g", "s")


def format_item(item):
    fields = ", ".join(
        f"{key}:{json.dumps(item.get(key), ensure_ascii=False)}" for key in FIELDS
    )
    return f"{{{fields}}},"


def item_key(item):
    return (item.get("y"), (item.get("t") or "").strip().lower())


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 sync_customitems.py app_data.json", file=sys.stderr)
        sys.exit(1)

    data_path = Path(sys.argv[1])
    app_data = json.loads(data_path.read_text())
    custom_items = app_data.get("customItems", [])

    promoted = [i for i in custom_items if not i.get("p")]
    still_pending = [i for i in custom_items if i.get("p")]

    synced = json.loads(SYNCED_ITEMS.read_text()) if SYNCED_ITEMS.exists() else []

    # Keyed merge: a title already promoted is updated in place, so a run
    # that fills in a previously-missing score corrects the entry rather
    # than adding a second copy of the same title.
    by_key = {item_key(i): i for i in synced}
    added, updated = 0, 0
    for item in promoted:
        clean = {k: item.get(k) for k in FIELDS}
        key = item_key(clean)
        if key in by_key:
            if by_key[key] != clean:
                by_key[key] = clean
                updated += 1
        else:
            by_key[key] = clean
            added += 1

    merged = list(by_key.values())
    new_block = "\n".join([START_MARKER] + [format_item(i) for i in merged] + [END_MARKER])

    src = INDEX_HTML.read_text()
    if START_MARKER in src:
        start = src.index(START_MARKER)
        end = src.index(END_MARKER) + len(END_MARKER)
        updated_src = src[:start] + new_block + src[end:]
    else:
        marker = "\n];"
        idx = src.index(marker, src.index("const ITEMS = ["))
        updated_src = src[:idx] + "\n\n" + new_block + src[idx:]

    # Promoted items now live in ITEMS, so they must be dropped from the
    # app-data blob or the app would render each of them twice.
    new_app_data = {"overrides": app_data.get("overrides", {}), "customItems": still_pending}
    if not APP_DATA_RE.search(updated_src):
        print("Could not find the app-data script tag in index.html", file=sys.stderr)
        sys.exit(1)
    replacement_json = json.dumps(new_app_data)
    updated_src = APP_DATA_RE.sub(
        lambda m: m.group(1) + replacement_json.replace("\\", "\\\\") + m.group(3),
        updated_src,
        count=1,
    )

    SYNCED_ITEMS.write_text(json.dumps(merged, indent=2, ensure_ascii=False) + "\n")
    INDEX_HTML.write_text(updated_src)
    data_path.write_text(json.dumps(new_app_data, indent=2))
    print(
        f"synced: {added} added, {updated} updated, {len(merged)} total in ITEMS; "
        f"{len(still_pending)} still pending"
    )


if __name__ == "__main__":
    main()
